### ISSUE TITLE
The resulting model

### ISSUE THREAD

**Issue by GantMan** [alexkimxyz/nsfw_data_scrapper#10]
Just wondering.  Did you want to link to your resulting model?

If not and you won't: would it be ok if I trained a model independently and sent a PR to link to my resulting model?   I love the scripts for researchers, however, some might want the result.

**Comment by alex000kim** [comment]
No, I won't be providing links to a model or the data itself. 
However, feel free to train your own and create a PR.
Please make sure that the code is simple to use and the results are easily reproducible.
