### ISSUE TITLE
Can you create a torrent of that data?

### ISSUE THREAD

**Issue by ParmuSingh** [alexkimxyz/nsfw_data_scrapper#12]
Downloading all this takes a lot of time and your script seems to be breaking sometimes. Sometimes it says its downloading but nothing really happens. It'll be great if you create a torrent of the data.

**Comment by alex000kim** [comment]
Did you pull the latest changes that added a timeout to wget?
For legal reasons, I can't distribute the data itself since I don't have the rights to the images.

**Comment by ParmuSingh** [comment]
Ah I happen to be using an older version. Aright thanks.

**Comment by GantMan** [comment]
Did you ever get the data @ParmuSingh ?

**Comment by ParmuSingh** [comment]
@GantMan no

**Comment by GantMan** [comment]
Message me on Twitter.  I’ll see if I can help

**Comment by ParmuSingh** [comment]
@GantMan yk I can't really just find you on twitter. Hit me up at @ParamdeepO.

**Comment by GantMan** [comment]
Following you.  I'm https://twitter.com/GantLaborde

**Comment by GantMan** [comment]
found this 
[NSFW_March_2019.7z.torrent.zip](https://github.com/alexkimxyz/nsfw_data_scraper/files/2931824/NSFW_March_2019.7z.torrent.zip)

**Comment by ParmuSingh** [comment]
@GantMan Thanks man!

**Comment by JieJayCao** [comment]
@ParmuSingh COOL

**Comment by JieCaoSec** [comment]
@GantMan This torrent has no speed, how to solve this problem!
