### ISSUE TITLE
Storing Data on Github doesn't seem like a great idea.

### ISSUE THREAD

**Issue by Dmphillips** [alexkimxyz/nsfw_data_scrapper#14]
The files that are stored in raw_data probably should be in the git ignore, mostly because github isn't a database. Instead I think that the raw_data directory should be the output folder.

**Comment by codeman1989** [comment]
It's the link of image,if you want the real data,you have to download it by your self.

**Comment by QGB** [comment]
本商品无评价入口，不计销量

**Comment by puguojingm** [comment]
你的脚本好像没有断点续传

**Comment by cjy513203427** [comment]
Good Sharing,I appreciate that
