### ISSUE TITLE
About download picture

### ISSUE THREAD

**Issue by kingroc711** [alexkimxyz/nsfw_data_scrapper#20]
Thanks your project help me. I am from China. I am not good at English, But I have some questions.
1.About cmd '1_get_urls.sh', the name is get url, but not really to get url list, because it use ripme.jar, it can get a lot of videos and picture, but now it not work.
2. Now 1_get_urls.sh do not work, but if you to run this cmd, it make 'neutral' 'drawings' 'sexy'.... all url_xxx.txt empty.  make cmd '2_download_from_urls.sh' do not work.
3. About cmd '5_create_train.sh'. in '1_get_urls.sh' use ripme.jar it download a lot of videos, but video can not be recognized, I can do this work. I know how to video to pictures and gif to pictures. 

your project is very very good, lost of company need your project get picture dataset and train self model.

**Comment by alex000kim** [comment]
1. Yes, ripme will initially get all media URLs such as videos and animations (gifs), but this line filters everything to only leave *.jpeg and *.jpg URLs: https://github.com/alexkimxyz/nsfw_data_scrapper/blob/master/scripts/1_get_urls.sh#L34
2. I ran the scripts a couple of time already and haven't seen this issue. Please make sure you follow the instructions carefully.
3. As I already said, `1_get_urls.sh` won't write and non-image URLs to `url_xxx.txt` files.

**Comment by kingroc711** [comment]
Thank you for your reply。

1. ` 1_get_urls.sh` [ line 33 and 34](https://github.com/alexkimxyz/nsfw_data_scrapper/blob/master/scripts/1_get_urls.sh#L33) make url_xxx.txt empty, because line 33 can not find anything by name "urls.txt", and line 34 writ result to url_xxx.txt `> "$urls_file"`, you can try `>>`  replace `>`
2. Why you ran the scripts a couple of time haven't seen this issue, because you not in China. In `1_get_urls.sh`  has two `for cycles`, first cycle spend a lot of time, but in china failure is fast, and run second cycle, the second cycle make url_xxx.txt NULL.

Follow my question:
1. I think first  cycle in 1_get_urls.sh is very good, Why need second cycle?
2.Why only get *.jpeg and *.jpg. Videos is good resources.
