### ISSUE TITLE
Details on this datasets

### ISSUE THREAD

**Issue by TanFluent** [alexkimxyz/nsfw_data_scrapper#23]
hi, 
  Thank you very much for your amazing works on collecting tons of images and labeling it. 
  And, should you please tell us more about the details on how you get it done? cus, i can't get more information on your "readme".
  for example, 
     Where this images source from? 
     Relationship with other open source datasets(like NPDI )? 
     Why choose these labels? how to label it(by manual/by machine)?
     Any experiment on this data?....
 It would be really helpful to figure out all these question before we using it

**Comment by TanFluent** [comment]
@alexkimxyz

**Comment by alex000kim** [comment]
- Sources of images can be any URLs of albums/collections supported by ripme
- As far as I know NPDI is a video dataset with three classes (porn, non-porn-easy, non-porn-difficult), this one has no relationship to NPDI

**Comment by TanFluent** [comment]
> * Sources of images can be any URLs of albums/collections supported by ripme
> * As far as I know NPDI is a video dataset with three classes (porn, non-porn-easy, non-porn-difficult), this one has no relationship to NPDI

Thank you for your quick reply! It really help me out. 
Have a nice day ! lol
