### ISSUE TITLE
Data Bias - Females in Porn

### ISSUE THREAD

**Issue by GantMan** [alexkimxyz/nsfw_data_scrapper#30]
It seems the data has a bit of bias for females in porn.
Link to issue for reference:  https://github.com/infinitered/nsfwjs/issues/16

It seems the scraper should be adjusted to counter-balance this bias.

**Comment by alex000kim** [comment]
I don't think there is much that can be done here.
Whatever model you train it will still be a garbage-in-garbage-out type of system.
I did add a disclaimer to the README though.

**Comment by GantMan** [comment]
I feel like more neutral women photos might help.  Thoughts?

**Comment by alex000kim** [comment]
Of course, it might.
I encourage people to contribute links to various *.txt files in https://github.com/alexkimxyz/nsfw_data_scraper/tree/master/scripts/source_urls/ in order to reduce the overall error and bias.
that said, there will always be some kind of bias.

**Comment by GantMan** [comment]
Sounds good.  Hopefully, this will help make a call to action on the data.
