### ISSUE TITLE
Adding new categories for NSFW Images and Drawing.

### ISSUE THREAD

**Issue by loretoparisi** [alexkimxyz/nsfw_data_scrapper#33]
Hello, in the past I was using Yahoo! [OpenNSFW](https://github.com/yahoo/open_nsfw) to detect NSFW content. Just few categories were defined in the training set, while this dataset has a better classification, thank you for this dataset! 
This new classification better works in real-world! I would like to further fine-tune the Keras model I have for other specific categories, like _NSFW Drawings_ (like nazi symbols, etc.) or new _NSFW Images_ categories (like guns, rifles, etc.). Do you have any reference for these categories?
Thank you.

**Comment by alex000kim** [comment]
@loretoparisi There might be websites that have albums containing images for the categories you describe. Here is the list of websites supported by Ripme: https://github.com/ripmeapp/ripme/wiki/Supported-Sites
Alternatively, check out this command-line tool to grab images from google: https://github.com/hardikvasa/google-images-download
