### ISSUE TITLE
Animated Gif images not supported

### ISSUE THREAD

**Issue by jiangyurong609** [alexkimxyz/nsfw_data_scrapper#34]
I found script 5 only checks corrupted jpeg, and did not differentiate the actual image types. Moreover, some animated gifs also get added with jpeg extension blindly. Tensorflow image reader doesn't support animated gif, so I'm wondering if checking and removing animated gif is necessary for script 5? If needed, I can open a PR. Thanks

**Comment by alex000kim** [comment]
Hi, please go ahead and submit a PR. Thanks.
