### ISSUE TITLE
xargs: wget: No such file or directory

### ISSUE THREAD

**Issue by KeepGoingCSU** [alexkimxyz/nsfw_data_scrapper#36]
when i first run the `bash 2_download_from_urls.sh` in my mac, i got
```
Class: neutral. Total # of urls:    20960
Downloading images...
xargs: wget: No such file or directory
Class: drawings. Total # of urls:    25732
Downloading images...
xargs: wget: No such file or directory
Class: sexy. Total # of urls:    19554
Downloading images...
xargs: wget: No such file or directory
Class: porn. Total # of urls:   116521
Downloading images...
xargs: wget: No such file or directory
Class: hentai. Total # of urls:    45228
Downloading images...
xargs: wget: No such file or directory
```
thanks for your answer

**Comment by xqtbox** [comment]
How to solve this problem？

**Comment by bkraszewski** [comment]
@xqtbox did you find the answer?

For future visitors - run this script via docker as presented in readme, so instead of:
    ./2_download_from_urls.sh 

use 
    docker run -v $(pwd):/root/nsfw_data_scraper docker_nsfw_data_scraper scripts/2_download_from_urls.sh 

Don't forget to make docker build first:
    docker build . -t docker_nsfw_data_scraper
