### ISSUE TITLE
anybody has downloaded the imgs? I cannot access reddit for some reason.

### ISSUE THREAD

**Issue by Edwardmark** [alexkimxyz/nsfw_data_scrapper#39]
anybody has downloaded the imgs? I cannot access reddit for some reason.
Is there a onedrive or google drive link for the data?
Thanks.

**Comment by Assembles** [comment]
you are so fucking lazy

**Comment by CodingMoeButa** [comment]
42GB. Downloading needs 5 days.

**Comment by luoyoumeng** [comment]
> 42GB。下载需要5天。

兄弟，你有下载完的数据集图片吗

**Comment by yyarrow** [comment]
您好，我是元棪，您的邮件已经收到。

**Comment by zhouqimark** [comment]
你好，如果你收到这封邮件。可能 只是因为我想测试一下假期自动回复功能。。

**Comment by moluzhang** [comment]
你好，我是张亚乐，你的来信我已收到，我会尽快回复你的来信！

**Comment by longems** [comment]
收到啦~~陆云龙

**Comment by Huterox** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by mcxen** [comment]
> 

Can you send me one? In some way.😇 i would thank you greatly

**Comment by longems** [comment]
收到啦~~陆云龙

**Comment by yyarrow** [comment]
您好，我是元棪，您的邮件已经收到。

**Comment by moluzhang** [comment]
你好，我是张亚乐，你的来信我已收到，我会尽快回复你的来信！

**Comment by Huterox** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by liuxilu** [comment]
养蛊是吧

**Comment by luoyoumeng** [comment]
？



---Original---
From: ***@***.***&gt;
Date: Tue, Jan 4, 2022 19:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alex000kim/nsfw_data_scraper] anybody has downloaded the imgs? Icannot access reddit for some reason. (#39)




 
养蛊是吧
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yyarrow** [comment]
您好，我是元棪，您的邮件已经收到。

**Comment by zhouqimark** [comment]
你好，如果你收到这封邮件。可能 只是因为我想测试一下假期自动回复功能。。

**Comment by Huterox** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by lanlanmist** [comment]
hello，may I have a copy. Thank u  very much.

**Comment by moluzhang** [comment]
你好，我是张亚乐，你的来信我已收到，我会尽快回复你的来信！

**Comment by Huterox** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by longems** [comment]
收到啦~~陆云龙

**Comment by yyarrow** [comment]
您好，我是元棪，您的邮件已经收到。

**Comment by zhouqimark** [comment]
你好，如果你收到这封邮件。可能 只是因为我想测试一下假期自动回复功能。。
