### ISSUE TITLE
Can anybody share trained model?

### ISSUE THREAD

**Issue by isong0623** [alexkimxyz/nsfw_data_scrapper#46]

**Comment by yzevm** [comment]
@isong0623  https://github.com/gantman/nsfw_model

**Comment by mehdikhanahmadzadeh** [comment]
Hi @YegorZaremba 
I hope you are well and healthy.

I have an NSFW database and I want to label them. Can I use your train model ??
 could you provide me the weights and parameters of trained model ???

**Comment by mehdikhanahmadzadeh** [comment]
Hi @YegorZaremba 

can i use this Link that sent by you for Labeling my own NSFW dataset??

**Comment by yzevm** [comment]
Hi @mehdikhanahmadzadeh Its GantMan's repository, I think its okey, license is MIT

**Comment by mehdikhanahmadzadeh** [comment]
thanks dear @YegorZaremba
