### ISSUE TITLE
Has anyone downloaded the images. I want the images but do not want to run the docker script. 

### ISSUE THREAD

**Issue by KKhushhalR2405** [alexkimxyz/nsfw_data_scrapper#51]

**Comment by yuxiaoyuan0406** [comment]
you are so f*cking lazy

**Comment by jkhaui** [comment]
^ Lmao

But in all honesty, the image dataset is probably what 90% of people are here for. The great thing about using the scripts is you can manually prune the url lists to an acceptable size if you only need to download - for example - 1,000  images in each category.
However, if pulling a Docker Image is too much work, you can try this dataset: https://archive.org/details/NudeNet_classifier_dataset_v1

**Comment by KKhushhalR2405** [comment]
> ^ Lmao
> 
> But in all honesty, the image dataset is probably what 90% of people are here for. The great thing about using the scripts is you can manually prune the url lists to an acceptable size if you only need to download - for example - 1,000 images in each category.
> However, if pulling a Docker Image is too much work, you can try this dataset: https://archive.org/details/NudeNet_classifier_dataset_v1

Thanks

**Comment by gengyanlei** [comment]
![image](https://user-images.githubusercontent.com/22360785/103986066-105efd80-51c5-11eb-810b-d79a8a96d8a2.png)
