### ISSUE TITLE
有点厉害了

### ISSUE THREAD

**Issue by kokokele** [alexkimxyz/nsfw_data_scrapper#8]

**Comment by mrzeta** [comment]
你又调皮😄
can not down load - - only support direct visited.

**Comment by WdBlink** [comment]
慕名前来

**Comment by kokokele** [comment]
这star 数，牛

**Comment by kasuganosoras** [comment]
有生之年终于看到有人在 Github 上开车了

**Comment by kaedea** [comment]
慕名而来 +1s

**Comment by alphardex** [comment]
老哥稳

**Comment by alex000kim** [comment]
Please use English when writing your comment, otherwise, I won't be able to help you. Thanks.

**Comment by zhr-coder** [comment]
Please don't use issue to talk rubbish. The purpose of issue function is to communicate technical and code issues.
求求你们别再跑GitHub开issue用中文说些废话骚扰作者了好吗？这么搞以后说中文的正经话题也要被作者们屏蔽了！issue是用来交流代码相关的。

**Comment by QGB** [comment]
nsfw_data_scrapper

**Comment by wangjitoan** [comment]
hi
